// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/1/2024, 11:15:48 AM
const configMerger = require("/workspaces/sbsrojobrono.github.io/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/workspaces/sbsrojobrono.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/plugins/**/*.{js,ts,mjs}","/workspaces/sbsrojobrono.github.io/composables/**/*.{js,ts,mjs}","/workspaces/sbsrojobrono.github.io/utils/**/*.{js,ts,mjs}","/workspaces/sbsrojobrono.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspaces/sbsrojobrono.github.io/app.config.{js,ts,mjs}"] }));

module.exports = config
